In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [2]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a

tensor([1., 1., 1.])

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

After importing the `torch` module, we call a function that creates a (one-dimensional) tensor of size 3 filled with the value `1.0`. We can access an element using its zero-based index or assign a new value to it. Although on the surface this example doesn’t differ much from a list of number objects, under the hood things are completely different.

# Another way to define tensor variables

In [3]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [7]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
type(points[3])

torch.Tensor

We also can pass Python list as a constructor

In [11]:
points2 = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points2

tensor([4., 1., 5., 3., 2., 1.])

In [14]:
type(float(points2[0]))

float

In [15]:
points2.shape

torch.Size([6])

# Define 2D Tensor

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points.shape

torch.Size([3, 2])

This informs us about the size of the tensor along each dimension. We could also use
`zeros` or `ones` to initialize the tensor, providing the size as a tuple:

In [18]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Now we can access an individual element in the tensor using two indices:

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points[0, 1]

tensor(1.)

In [21]:
points[0]

tensor([4., 1.])

# Indexing Tensor

Reminder in Python list

In [22]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [23]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [31]:
some_list[1:4] # call 1st index - (4th index-1) [bcs start from zero]

[1, 2, 3]

In [32]:
some_list[1:] # call 1st index - end

[1, 2, 3, 4, 5]

In [34]:
some_list[:4] # call zero index - (4th index-1) [bcs start from zero]

[0, 1, 2, 3]

In [36]:
some_list[:-1] # -1 means last index which is 5

[0, 1, 2, 3, 4]

In [38]:
some_list[1:4:2] # call 1st index - (4th index-1) [bcs start from zero] with step 2

[1, 3]

To achieve our goal, we can use the same notation for PyTorch tensors, with the added benefit that, just as in NumPy and other Python scientific libraries, we can use range indexing for each of the tensor’s dimensions:

In [39]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [42]:
points[1:] # all rows after the first, implicitly all columns

tensor([[5., 3.],
        [2., 1.]])

In [46]:
points[1:, :] # All rows after the first, all columns

tensor([[5., 3.],
        [2., 1.]])

In [47]:
points[1:, 0] # all rows after first, zero column

tensor([5., 2.])

In [49]:
points[None] # add dimension 1, like unsqueeze?

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [ ]:
points[None].shape